title: A Simple Exercise on FX Attribution
author: Martin Rinaldi
logo: UBC.jpeg

# Increase font size for better readability
html_theme_options:
  font_size: 22px

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
  
theme: Merlot

# Add a bibtex file so that we can create citations
bibtex_bibfiles: references.bib
